stages:
  ingestion:
    cmd: python -m src.ingestion.ingest
    deps:
      - src/ingestion/ingest.py
      - data/raw
    outs:
      - data/processed/pages/pages.jsonl

  cleaning:
    cmd: python -m src.cleaning.clean
    deps:
      - src/cleaning/clean.py
      - data/processed/pages/pages.jsonl
    outs:
      - data/processed/chunks/chunks.jsonl

  embeddings:
    cmd: python -m src.embeddings.embed
    deps:
      - src/embeddings/embed.py
      - data/processed/chunks/chunks.jsonl
    outs:
      - data/embeddings/embeddings.npy
      - data/embeddings/metadata.json

  vector_store:
    cmd: python -m src.embeddings.store
    deps:
      - src/embeddings/store.py
      - configs/embeddings.yaml
      - data/embeddings/embeddings.npy
      - data/embeddings/metadata.json
      - data/processed/chunks/chunks.jsonl
    outs:
      - data/chroma_db:
          cache: false